# Generated by Django 3.2.14 on 2022-08-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='city',
            new_name='user_city',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='country',
            new_name='user_country',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='house_name',
            new_name='user_house_name',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='post_code',
            new_name='user_post_code',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='street_address_1',
            new_name='user_street_address_1',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='street_address_2',
            new_name='user_street_address_2',
        ),
    ]
