# Generated by Django 3.2.14 on 2022-08-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220801_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='first_name',
            new_name='user_full_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
    ]
