# Generated by Django 3.2.14 on 2022-08-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220801_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user_full_name',
            new_name='user_phone_number',
        ),
    ]
