# Generated by Django 3.2.14 on 2022-07-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220730_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
